// <auto-generated />
namespace Rate_A_Cop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IsAnonymous : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsAnonymous));
        
        string IMigrationMetadata.Id
        {
            get { return "201608181349383_IsAnonymous"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
